@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdhcmNpYUBnbWFpbC5jb20iLCJpZCI6MTEsImlhdCI6MTY5MjQ3ODEzMCwiZXhwIjoxNjkyNTY0NTMwfQ.3VQEqm6AdcKeeXgUvh0P9OKeWD2X1uSqZLhpucSHxKM
#### Obtener todos los usuarios
GET http://localhost:3000/api/v1/users
Authorization: Bearer {{accessToken}}


### Obtener usuario por su id
GET http://localhost:3000/api/v1/users/2
Authorization: Bearer {{accessToken}}

### Crear Usaurio
POST  http://localhost:3000/api/v1/users
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name":"jesús Maria",
    "password":"123456",
    "email":"prueba10@gmail.com",
    "primer_apellido":"Quintana",
    "segundo_apellido":"Esquiliche",
    "user_name":"jesquiliche"
}

### Actualizar Usuario
PATCH http://localhost:3000/api/v1/users/10
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name":"jesús Antonio",
    "password":"123456",
    "email":"prueba11@gmail.com",
    "primer_apellido":"Garcia",
    "segundo_apellido":"Esquiliche",
    "user_name":"jesquiliche"
}

### Borrar usuario
DELETE http://localhost:3000/api/v1/users/10
Authorization: Bearer {{accessToken}}

### Registrar Usaurio
POST http://localhost:3000/api/v1/auth/register
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name":"Antonio",
   
   "user_name":"",
    "password":"123456",
    "email":"garci20@gmail.com",
    "primer_apellido":"Garcia",
    "segundo_apellido":"Garcia",
    "user_name":"garcia"
}

### Registrar Usaurio
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "password":"123456",
    "email":"garcia@gmail.com"

}

### listado de categorías
GET http://localhost:3000/api/v1/categorias
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Vista de una categoría por su id
GET http://localhost:3000/api/v1/categorias/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Vista de una categoría por su id
GET http://localhost:3000/api/v1/categorias/1/subcategorias
Content-Type: application/json
Authorization: Bearer {{accessToken}}



### listado de categorías
POST http://localhost:3000/api/v1/categorias
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "nombre":"Televisores",
    "descripcion":"Descripción de Televisores ",
    "imagen":"Imagen"
}

### listado de categorías
PATCH  http://localhost:3000/api/v1/categorias/2
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "nombre":"Televisores PLASMA",
    "descripcion":"Descripción de Televisores "
}


### listado de categorías
DELETE  http://localhost:3000/api/v1/categorias/2
Content-Type: application/json

### listado de subcategorías
GET http://localhost:3000/api/v1/subcategorias
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Crear Subcategoria
POST http://localhost:3000/api/v1/subcategorias
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "nombre":"Subcategoria de pruebas",
    "descripcion":"Descripción de Televisores ",
    "imagen":"Imagen",
    "categoria_id":1
}

### Modificar subcategoría
PATCH  http://localhost:3000/api/v1/subcategorias/2
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "nombre":"Subcategoria de pruebas 2",
    "descripcion":"Descripción de Televisores ",
    "imagen":"Imagen",
    "categoria_id":1
}

### Modificar subcategoría
DELETE  http://localhost:3000/api/v1/subcategorias/2
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### Listar estados
GET   http://localhost:3000/api/v1/estados
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Crear estados
POST   http://localhost:3000/api/v1/estados
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "titulo":"Necesita reparación"
}


### Modificar estados
PATCH    http://localhost:3000/api/v1/estados/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "titulo":"Necesita reparación 2"
}

### Borrar estados
DELETE    http://localhost:3000/api/v1/estados/6
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Listar provincias
GET    http://localhost:3000/api/v1/provincias
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Listar provincias
GET    http://localhost:3000/api/v1/poblaciones
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Post poblaciones
POST    http://localhost:3000/api/v1/poblaciones
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "codigo":"08921",
    "nombre":"Santa Coloma de Gramenet",
    "cod_provincia":"02"
}
